apiVersion: apps/v1
kind: Deployment
metadata:
  name: appb
  labels: 
    name: appb
spec:
  replicas: 1
  minReadySeconds: 5
  strategy:
    type: RollingUpdate
    rollingUpdate:
      maxSurge: 1
      maxUnavailable: 1
  spec:
  selector:
    matchLabels:
      name: appb
  template:
    metadata:
      labels:
        name: appb
        app: dbg
    spec:
      containers:
      - name: appb
        image: {{ .Values.image.repository }}:{{ .Values.image.tag }}
        ports:
          - containerPort: 80
            name: http         
            protocol: TCP
        env: 
          - name: "SERVICEENDPOINTHOST"
            value: "svcc"
          - name: "SERVICEENDPOINTPATH"
            value: "/api/whoareu"              
          - name: "COLOR"
            value: "green"
          - name: "SERVICEENDPOINTPORT"
            value: "80"


