apiVersion: v1
kind: Service
metadata:
  name: svcb
  labels:
    name: svcb
spec:
  selector:
    name: appb
  type: ClusterIP
  ports:
   - port: 80
     name: http
     targetPort: 80
     protocol: TCP
