apiVersion: v1
kind: Service
metadata:
  # name: mysvcname
  # name: {{ .Values.servicename }}
  name: {{ template "debugcontainer.fullname" . }}
  labels:
    app: {{ template "debugcontainer.name" . }}
    chart: {{ template "debugcontainer.chart" . }}
    release: {{ .Release.Name }}
    heritage: {{ .Release.Service }}
spec:
  type: {{ .Values.service.type }}
  ports:
    - port: {{ .Values.service.port }}
      targetPort: http
      protocol: TCP
      name: http
  selector:
    app: {{ template "debugcontainer.name" . }}
    release: {{ .Release.Name }}
